### ISSUE TITLE
Revisions for SCHEMA

### ISSUE THREAD

**Issue by samsongs1991** [kcheng16/paw-perty#2]
1. Table names should be snake_cased.
2. In the bullets under the users table, "email" and "unique: true" should be highlighted.
3. listings table needs bullets under the table to indicate what is indexed and what table the foreign_keys reference. Same for reviews table.
4. Follow the bluebird wiki example - https://github.com/appacademy/bluebird/wiki

**Comment by samsongs1991** [comment]
Last thing to edit would be removing "table" from your table names.

**Comment by kcheng16** [comment]
'table' has been removed
