### ISSUE TITLE
Question about MVPs

### ISSUE THREAD

**Issue by samsongs1991** [kcheng16/paw-perty#3]
I see you're including the ability for a user to make reservations. Does that mean you're planning on implementing a checkout cart as well?

**Comment by kcheng16** [comment]
I don't plan to implement a checkout cart. I'm thinking of just adding the intended reservation to the user's reservation list upon clicking 'reserve', for now. I was thinking I needed a way to keep track of a user's reservations. What's your opinion?

**Comment by samsongs1991** [comment]
Okay I just wanted clarification on that. That is good actually. Adding a checkout cart would take another 2 days probably. Thanks!
