### ISSUE TITLE
Revisions for BACKEND ROUTES

### ISSUE THREAD

**Issue by samsongs1991** [kcheng16/paw-perty#4]
I see that in your "listings" backend routes, you have one for "GET api/listings/:query" which is superfluous and also conflicts with "GET api/listings/:id". 

1. When you make a "GET request" to "api/listings" it is possible to filter the listings you get back without a ":query" wildcard.
2. When you have a "GET request" to "api/listings/:id" AND to "api/listings/:query" there is a problem. Let's say you make an ajax request to your backend database 

```js
$.ajax({
   type: "GET", 
   url: "api/listings/5"
})
```

...there's no way for your code to know if the wildcard "5" is for the ":id" or the ":query" wildcard. Hence, you cannot do this.

*I'll check off your backend routes after you remove this "api/listings/:query" route.

**Comment by kcheng16** [comment]
That makes sense and was very clear! Thanks! I was very unfamiliar with how 'filtering' would work in a search. I'll go ahead and remove that backend-route right now. Thanks Sam!
